# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u7f16\u53f7')),
                ('name', models.TextField(verbose_name='\u540d\u79f0')),
                ('remark', models.TextField(verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='\u7528\u6237\u7f16\u53f7')),
                ('pwd', models.TextField(verbose_name='\u5bc6\u7801')),
                ('authority', models.IntegerField(verbose_name='\u6743\u9650')),
                ('name', models.TextField(verbose_name='\u59d3\u540d')),
                ('sex', models.IntegerField(verbose_name='\u6027\u522b')),
                ('major', models.TextField(verbose_name='\u4e13\u4e1a')),
                ('source', models.TextField(verbose_name='\u751f\u6e90\u5730')),
                ('apartment', models.TextField(verbose_name='\u5b66\u9662')),
            ],
        ),
    ]
