# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='*\u7f16\u53f7')),
                ('name', models.TextField(verbose_name='*\u540d\u79f0')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='DorArrange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('dor_id', models.AutoField(primary_key=True, serialize=False, verbose_name='*\u5bbf\u820d\u7f16\u53f7')),
                ('name', models.IntegerField(verbose_name='*\u5bbf\u820d\u540d')),
                ('capacity', models.IntegerField(verbose_name='*\u5bb9\u91cf')),
                ('count', models.IntegerField(verbose_name='*\u5df2\u7528\u7a7a\u95f4')),
                ('state', models.IntegerField(verbose_name='*\u53ef\u7528\u72b6\u6001')),
                ('buil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='*\u95ee\u9898\u7f16\u53f7')),
                ('content', models.TextField(verbose_name='*\u5185\u5bb9')),
                ('option', models.TextField(verbose_name='*\u9009\u9879')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='*\u7528\u6237\u7f16\u53f7')),
                ('pwd', models.TextField(verbose_name='*\u5bc6\u7801')),
                ('authority', models.IntegerField(verbose_name='*\u6743\u9650')),
                ('name', models.TextField(verbose_name='*\u59d3\u540d')),
                ('sex', models.IntegerField(verbose_name='*\u6027\u522b')),
                ('major', models.TextField(blank=True, null=True, verbose_name='\u4e13\u4e1a')),
                ('source', models.TextField(blank=True, null=True, verbose_name='\u751f\u6e90\u5730')),
                ('apartment', models.TextField(blank=True, null=True, verbose_name='\u5b66\u9662')),
            ],
        ),
        migrations.CreateModel(
            name='User_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='*\u7b54\u6848')),
                ('que_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.Question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.User')),
            ],
        ),
        migrations.AddField(
            model_name='dorarrange',
            name='dor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dormitory.Dormitory'),
        ),
        migrations.AddField(
            model_name='dorarrange',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dormitory.User'),
        ),
    ]
