# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0002_dormitory'),
    ]

    operations = [
        migrations.CreateModel(
            name='dor_arr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.dormitory')),
                ('uesr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.user')),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u95ee\u9898\u7f16\u53f7')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('option', models.TextField(verbose_name='\u9009\u9879')),
                ('remark', models.TextField(verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='user_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='\u7b54\u6848')),
                ('que_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.user')),
            ],
        ),
    ]
